//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdK.Tagger.SpotUploadService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Match", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Match : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SampleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AdK.Tagger.SpotUploadService.MatchPeriod> PeriodsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SampleID {
            get {
                return this.SampleIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SampleIDField, value) != true)) {
                    this.SampleIDField = value;
                    this.RaisePropertyChanged("SampleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Collections.Generic.List<AdK.Tagger.SpotUploadService.MatchPeriod> Periods {
            get {
                return this.PeriodsField;
            }
            set {
                if ((object.ReferenceEquals(this.PeriodsField, value) != true)) {
                    this.PeriodsField = value;
                    this.RaisePropertyChanged("Periods");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchPeriod", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MatchPeriod : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double SourceStartField;
        
        private double SourceEndField;
        
        private double DestinationStartField;
        
        private double DestinationEndField;
        
        private double BERField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double SourceStart {
            get {
                return this.SourceStartField;
            }
            set {
                if ((this.SourceStartField.Equals(value) != true)) {
                    this.SourceStartField = value;
                    this.RaisePropertyChanged("SourceStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double SourceEnd {
            get {
                return this.SourceEndField;
            }
            set {
                if ((this.SourceEndField.Equals(value) != true)) {
                    this.SourceEndField = value;
                    this.RaisePropertyChanged("SourceEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double DestinationStart {
            get {
                return this.DestinationStartField;
            }
            set {
                if ((this.DestinationStartField.Equals(value) != true)) {
                    this.DestinationStartField = value;
                    this.RaisePropertyChanged("DestinationStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double DestinationEnd {
            get {
                return this.DestinationEndField;
            }
            set {
                if ((this.DestinationEndField.Equals(value) != true)) {
                    this.DestinationEndField = value;
                    this.RaisePropertyChanged("DestinationEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double BER {
            get {
                return this.BERField;
            }
            set {
                if ((this.BERField.Equals(value) != true)) {
                    this.BERField = value;
                    this.RaisePropertyChanged("BER");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SpotUploadService.ServiceProviderSoap")]
    public interface ServiceProviderSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        AdK.Tagger.SpotUploadService.HelloWorldResponse HelloWorld(AdK.Tagger.SpotUploadService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        AdK.Tagger.SpotUploadService.LoginResponse Login(AdK.Tagger.SpotUploadService.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name ApiKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSample", ReplyAction="*")]
        AdK.Tagger.SpotUploadService.AddSampleResponse AddSample(AdK.Tagger.SpotUploadService.AddSampleRequest request);
        
        // CODEGEN: Generating message contract since element name ApiKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSampleFromURL", ReplyAction="*")]
        AdK.Tagger.SpotUploadService.AddSampleFromURLResponse AddSampleFromURL(AdK.Tagger.SpotUploadService.AddSampleFromURLRequest request);
        
        // CODEGEN: Generating message contract since element name ApiKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSampleStatus", ReplyAction="*")]
        AdK.Tagger.SpotUploadService.GetSampleStatusResponse GetSampleStatus(AdK.Tagger.SpotUploadService.GetSampleStatusRequest request);
        
        // CODEGEN: Generating message contract since element name ApiKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMatchesForSampleEx", ReplyAction="*")]
        AdK.Tagger.SpotUploadService.GetMatchesForSampleExResponse GetMatchesForSampleEx(AdK.Tagger.SpotUploadService.GetMatchesForSampleExRequest request);
        
        // CODEGEN: Generating message contract since element name ApiKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMatchesForSample", ReplyAction="*")]
        AdK.Tagger.SpotUploadService.GetMatchesForSampleResponse GetMatchesForSample(AdK.Tagger.SpotUploadService.GetMatchesForSampleRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUser", ReplyAction="*")]
        AdK.Tagger.SpotUploadService.CreateUserResponse CreateUser(AdK.Tagger.SpotUploadService.CreateUserRequest request);
        
        // CODEGEN: Generating message contract since element name ApiKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MatchingComplete", ReplyAction="*")]
        AdK.Tagger.SpotUploadService.MatchingCompleteResponse MatchingComplete(AdK.Tagger.SpotUploadService.MatchingCompleteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public AdK.Tagger.SpotUploadService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(AdK.Tagger.SpotUploadService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdK.Tagger.SpotUploadService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(AdK.Tagger.SpotUploadService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public AdK.Tagger.SpotUploadService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(AdK.Tagger.SpotUploadService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdK.Tagger.SpotUploadService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(AdK.Tagger.SpotUploadService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSampleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSample", Namespace="http://tempuri.org/", Order=0)]
        public AdK.Tagger.SpotUploadService.AddSampleRequestBody Body;
        
        public AddSampleRequest() {
        }
        
        public AddSampleRequest(AdK.Tagger.SpotUploadService.AddSampleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSampleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ApiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] AudioData;
        
        public AddSampleRequestBody() {
        }
        
        public AddSampleRequestBody(string ApiKey, byte[] AudioData) {
            this.ApiKey = ApiKey;
            this.AudioData = AudioData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSampleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSampleResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdK.Tagger.SpotUploadService.AddSampleResponseBody Body;
        
        public AddSampleResponse() {
        }
        
        public AddSampleResponse(AdK.Tagger.SpotUploadService.AddSampleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSampleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddSampleResult;
        
        public AddSampleResponseBody() {
        }
        
        public AddSampleResponseBody(string AddSampleResult) {
            this.AddSampleResult = AddSampleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSampleFromURLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSampleFromURL", Namespace="http://tempuri.org/", Order=0)]
        public AdK.Tagger.SpotUploadService.AddSampleFromURLRequestBody Body;
        
        public AddSampleFromURLRequest() {
        }
        
        public AddSampleFromURLRequest(AdK.Tagger.SpotUploadService.AddSampleFromURLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSampleFromURLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ApiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string URL;
        
        public AddSampleFromURLRequestBody() {
        }
        
        public AddSampleFromURLRequestBody(string ApiKey, string URL) {
            this.ApiKey = ApiKey;
            this.URL = URL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSampleFromURLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSampleFromURLResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdK.Tagger.SpotUploadService.AddSampleFromURLResponseBody Body;
        
        public AddSampleFromURLResponse() {
        }
        
        public AddSampleFromURLResponse(AdK.Tagger.SpotUploadService.AddSampleFromURLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSampleFromURLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddSampleFromURLResult;
        
        public AddSampleFromURLResponseBody() {
        }
        
        public AddSampleFromURLResponseBody(string AddSampleFromURLResult) {
            this.AddSampleFromURLResult = AddSampleFromURLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSampleStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSampleStatus", Namespace="http://tempuri.org/", Order=0)]
        public AdK.Tagger.SpotUploadService.GetSampleStatusRequestBody Body;
        
        public GetSampleStatusRequest() {
        }
        
        public GetSampleStatusRequest(AdK.Tagger.SpotUploadService.GetSampleStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSampleStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ApiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SampleID;
        
        public GetSampleStatusRequestBody() {
        }
        
        public GetSampleStatusRequestBody(string ApiKey, string SampleID) {
            this.ApiKey = ApiKey;
            this.SampleID = SampleID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSampleStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSampleStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdK.Tagger.SpotUploadService.GetSampleStatusResponseBody Body;
        
        public GetSampleStatusResponse() {
        }
        
        public GetSampleStatusResponse(AdK.Tagger.SpotUploadService.GetSampleStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSampleStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSampleStatusResult;
        
        public GetSampleStatusResponseBody() {
        }
        
        public GetSampleStatusResponseBody(string GetSampleStatusResult) {
            this.GetSampleStatusResult = GetSampleStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMatchesForSampleExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMatchesForSampleEx", Namespace="http://tempuri.org/", Order=0)]
        public AdK.Tagger.SpotUploadService.GetMatchesForSampleExRequestBody Body;
        
        public GetMatchesForSampleExRequest() {
        }
        
        public GetMatchesForSampleExRequest(AdK.Tagger.SpotUploadService.GetMatchesForSampleExRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMatchesForSampleExRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ApiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SampleID;
        
        public GetMatchesForSampleExRequestBody() {
        }
        
        public GetMatchesForSampleExRequestBody(string ApiKey, string SampleID) {
            this.ApiKey = ApiKey;
            this.SampleID = SampleID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMatchesForSampleExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMatchesForSampleExResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdK.Tagger.SpotUploadService.GetMatchesForSampleExResponseBody Body;
        
        public GetMatchesForSampleExResponse() {
        }
        
        public GetMatchesForSampleExResponse(AdK.Tagger.SpotUploadService.GetMatchesForSampleExResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMatchesForSampleExResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<AdK.Tagger.SpotUploadService.Match> GetMatchesForSampleExResult;
        
        public GetMatchesForSampleExResponseBody() {
        }
        
        public GetMatchesForSampleExResponseBody(System.Collections.Generic.List<AdK.Tagger.SpotUploadService.Match> GetMatchesForSampleExResult) {
            this.GetMatchesForSampleExResult = GetMatchesForSampleExResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMatchesForSampleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMatchesForSample", Namespace="http://tempuri.org/", Order=0)]
        public AdK.Tagger.SpotUploadService.GetMatchesForSampleRequestBody Body;
        
        public GetMatchesForSampleRequest() {
        }
        
        public GetMatchesForSampleRequest(AdK.Tagger.SpotUploadService.GetMatchesForSampleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMatchesForSampleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ApiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SampleID;
        
        public GetMatchesForSampleRequestBody() {
        }
        
        public GetMatchesForSampleRequestBody(string ApiKey, string SampleID) {
            this.ApiKey = ApiKey;
            this.SampleID = SampleID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMatchesForSampleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMatchesForSampleResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdK.Tagger.SpotUploadService.GetMatchesForSampleResponseBody Body;
        
        public GetMatchesForSampleResponse() {
        }
        
        public GetMatchesForSampleResponse(AdK.Tagger.SpotUploadService.GetMatchesForSampleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMatchesForSampleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AdK.Tagger.SpotUploadService.ArrayOfString GetMatchesForSampleResult;
        
        public GetMatchesForSampleResponseBody() {
        }
        
        public GetMatchesForSampleResponseBody(AdK.Tagger.SpotUploadService.ArrayOfString GetMatchesForSampleResult) {
            this.GetMatchesForSampleResult = GetMatchesForSampleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUser", Namespace="http://tempuri.org/", Order=0)]
        public AdK.Tagger.SpotUploadService.CreateUserRequestBody Body;
        
        public CreateUserRequest() {
        }
        
        public CreateUserRequest(AdK.Tagger.SpotUploadService.CreateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public CreateUserRequestBody() {
        }
        
        public CreateUserRequestBody(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdK.Tagger.SpotUploadService.CreateUserResponseBody Body;
        
        public CreateUserResponse() {
        }
        
        public CreateUserResponse(AdK.Tagger.SpotUploadService.CreateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateUserResult;
        
        public CreateUserResponseBody() {
        }
        
        public CreateUserResponseBody(string CreateUserResult) {
            this.CreateUserResult = CreateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MatchingCompleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MatchingComplete", Namespace="http://tempuri.org/", Order=0)]
        public AdK.Tagger.SpotUploadService.MatchingCompleteRequestBody Body;
        
        public MatchingCompleteRequest() {
        }
        
        public MatchingCompleteRequest(AdK.Tagger.SpotUploadService.MatchingCompleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MatchingCompleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ApiKey;
        
        public MatchingCompleteRequestBody() {
        }
        
        public MatchingCompleteRequestBody(string ApiKey) {
            this.ApiKey = ApiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MatchingCompleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MatchingCompleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdK.Tagger.SpotUploadService.MatchingCompleteResponseBody Body;
        
        public MatchingCompleteResponse() {
        }
        
        public MatchingCompleteResponse(AdK.Tagger.SpotUploadService.MatchingCompleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MatchingCompleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool MatchingCompleteResult;
        
        public MatchingCompleteResponseBody() {
        }
        
        public MatchingCompleteResponseBody(bool MatchingCompleteResult) {
            this.MatchingCompleteResult = MatchingCompleteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceProviderSoapChannel : AdK.Tagger.SpotUploadService.ServiceProviderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceProviderSoapClient : System.ServiceModel.ClientBase<AdK.Tagger.SpotUploadService.ServiceProviderSoap>, AdK.Tagger.SpotUploadService.ServiceProviderSoap {
        
        public ServiceProviderSoapClient() {
        }
        
        public ServiceProviderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceProviderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProviderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProviderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdK.Tagger.SpotUploadService.HelloWorldResponse AdK.Tagger.SpotUploadService.ServiceProviderSoap.HelloWorld(AdK.Tagger.SpotUploadService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            AdK.Tagger.SpotUploadService.HelloWorldRequest inValue = new AdK.Tagger.SpotUploadService.HelloWorldRequest();
            inValue.Body = new AdK.Tagger.SpotUploadService.HelloWorldRequestBody();
            AdK.Tagger.SpotUploadService.HelloWorldResponse retVal = ((AdK.Tagger.SpotUploadService.ServiceProviderSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdK.Tagger.SpotUploadService.LoginResponse AdK.Tagger.SpotUploadService.ServiceProviderSoap.Login(AdK.Tagger.SpotUploadService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string Username, string Password) {
            AdK.Tagger.SpotUploadService.LoginRequest inValue = new AdK.Tagger.SpotUploadService.LoginRequest();
            inValue.Body = new AdK.Tagger.SpotUploadService.LoginRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            AdK.Tagger.SpotUploadService.LoginResponse retVal = ((AdK.Tagger.SpotUploadService.ServiceProviderSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdK.Tagger.SpotUploadService.AddSampleResponse AdK.Tagger.SpotUploadService.ServiceProviderSoap.AddSample(AdK.Tagger.SpotUploadService.AddSampleRequest request) {
            return base.Channel.AddSample(request);
        }
        
        public string AddSample(string ApiKey, byte[] AudioData) {
            AdK.Tagger.SpotUploadService.AddSampleRequest inValue = new AdK.Tagger.SpotUploadService.AddSampleRequest();
            inValue.Body = new AdK.Tagger.SpotUploadService.AddSampleRequestBody();
            inValue.Body.ApiKey = ApiKey;
            inValue.Body.AudioData = AudioData;
            AdK.Tagger.SpotUploadService.AddSampleResponse retVal = ((AdK.Tagger.SpotUploadService.ServiceProviderSoap)(this)).AddSample(inValue);
            return retVal.Body.AddSampleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdK.Tagger.SpotUploadService.AddSampleFromURLResponse AdK.Tagger.SpotUploadService.ServiceProviderSoap.AddSampleFromURL(AdK.Tagger.SpotUploadService.AddSampleFromURLRequest request) {
            return base.Channel.AddSampleFromURL(request);
        }
        
        public string AddSampleFromURL(string ApiKey, string URL) {
            AdK.Tagger.SpotUploadService.AddSampleFromURLRequest inValue = new AdK.Tagger.SpotUploadService.AddSampleFromURLRequest();
            inValue.Body = new AdK.Tagger.SpotUploadService.AddSampleFromURLRequestBody();
            inValue.Body.ApiKey = ApiKey;
            inValue.Body.URL = URL;
            AdK.Tagger.SpotUploadService.AddSampleFromURLResponse retVal = ((AdK.Tagger.SpotUploadService.ServiceProviderSoap)(this)).AddSampleFromURL(inValue);
            return retVal.Body.AddSampleFromURLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdK.Tagger.SpotUploadService.GetSampleStatusResponse AdK.Tagger.SpotUploadService.ServiceProviderSoap.GetSampleStatus(AdK.Tagger.SpotUploadService.GetSampleStatusRequest request) {
            return base.Channel.GetSampleStatus(request);
        }
        
        public string GetSampleStatus(string ApiKey, string SampleID) {
            AdK.Tagger.SpotUploadService.GetSampleStatusRequest inValue = new AdK.Tagger.SpotUploadService.GetSampleStatusRequest();
            inValue.Body = new AdK.Tagger.SpotUploadService.GetSampleStatusRequestBody();
            inValue.Body.ApiKey = ApiKey;
            inValue.Body.SampleID = SampleID;
            AdK.Tagger.SpotUploadService.GetSampleStatusResponse retVal = ((AdK.Tagger.SpotUploadService.ServiceProviderSoap)(this)).GetSampleStatus(inValue);
            return retVal.Body.GetSampleStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdK.Tagger.SpotUploadService.GetMatchesForSampleExResponse AdK.Tagger.SpotUploadService.ServiceProviderSoap.GetMatchesForSampleEx(AdK.Tagger.SpotUploadService.GetMatchesForSampleExRequest request) {
            return base.Channel.GetMatchesForSampleEx(request);
        }
        
        public System.Collections.Generic.List<AdK.Tagger.SpotUploadService.Match> GetMatchesForSampleEx(string ApiKey, string SampleID) {
            AdK.Tagger.SpotUploadService.GetMatchesForSampleExRequest inValue = new AdK.Tagger.SpotUploadService.GetMatchesForSampleExRequest();
            inValue.Body = new AdK.Tagger.SpotUploadService.GetMatchesForSampleExRequestBody();
            inValue.Body.ApiKey = ApiKey;
            inValue.Body.SampleID = SampleID;
            AdK.Tagger.SpotUploadService.GetMatchesForSampleExResponse retVal = ((AdK.Tagger.SpotUploadService.ServiceProviderSoap)(this)).GetMatchesForSampleEx(inValue);
            return retVal.Body.GetMatchesForSampleExResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdK.Tagger.SpotUploadService.GetMatchesForSampleResponse AdK.Tagger.SpotUploadService.ServiceProviderSoap.GetMatchesForSample(AdK.Tagger.SpotUploadService.GetMatchesForSampleRequest request) {
            return base.Channel.GetMatchesForSample(request);
        }
        
        public AdK.Tagger.SpotUploadService.ArrayOfString GetMatchesForSample(string ApiKey, string SampleID) {
            AdK.Tagger.SpotUploadService.GetMatchesForSampleRequest inValue = new AdK.Tagger.SpotUploadService.GetMatchesForSampleRequest();
            inValue.Body = new AdK.Tagger.SpotUploadService.GetMatchesForSampleRequestBody();
            inValue.Body.ApiKey = ApiKey;
            inValue.Body.SampleID = SampleID;
            AdK.Tagger.SpotUploadService.GetMatchesForSampleResponse retVal = ((AdK.Tagger.SpotUploadService.ServiceProviderSoap)(this)).GetMatchesForSample(inValue);
            return retVal.Body.GetMatchesForSampleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdK.Tagger.SpotUploadService.CreateUserResponse AdK.Tagger.SpotUploadService.ServiceProviderSoap.CreateUser(AdK.Tagger.SpotUploadService.CreateUserRequest request) {
            return base.Channel.CreateUser(request);
        }
        
        public string CreateUser(string Username, string Password) {
            AdK.Tagger.SpotUploadService.CreateUserRequest inValue = new AdK.Tagger.SpotUploadService.CreateUserRequest();
            inValue.Body = new AdK.Tagger.SpotUploadService.CreateUserRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            AdK.Tagger.SpotUploadService.CreateUserResponse retVal = ((AdK.Tagger.SpotUploadService.ServiceProviderSoap)(this)).CreateUser(inValue);
            return retVal.Body.CreateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdK.Tagger.SpotUploadService.MatchingCompleteResponse AdK.Tagger.SpotUploadService.ServiceProviderSoap.MatchingComplete(AdK.Tagger.SpotUploadService.MatchingCompleteRequest request) {
            return base.Channel.MatchingComplete(request);
        }
        
        public bool MatchingComplete(string ApiKey) {
            AdK.Tagger.SpotUploadService.MatchingCompleteRequest inValue = new AdK.Tagger.SpotUploadService.MatchingCompleteRequest();
            inValue.Body = new AdK.Tagger.SpotUploadService.MatchingCompleteRequestBody();
            inValue.Body.ApiKey = ApiKey;
            AdK.Tagger.SpotUploadService.MatchingCompleteResponse retVal = ((AdK.Tagger.SpotUploadService.ServiceProviderSoap)(this)).MatchingComplete(inValue);
            return retVal.Body.MatchingCompleteResult;
        }
    }
}
